### ISSUE TITLE
Requested code extension: horizontal ground surface displacements

### ISSUE THREAD

**Issue by fdinger** [jkennel/earthtide#1]
Thanks for sharing this new R package, which I am looking for since "solidearthtide" has been archived!

I wonder if it is possible to add two further method(s) to the calc_earthtide(..) function which output the tide-induced ground surface displacement in North-South and East-West direction analogously to method = vertical_displacement.

**Comment by jkennel** [comment]
Thank you for the request.  I will try to add these options in the next release, but it might be some time before I get to it.

**Comment by jkennel** [comment]
I have now added the options "horizontal_displacement", "n_s_displacement", "e_w_displacement".  It will likely be a few weeks before I submit to CRAN.

- _horizontal_displacement_ uses the specified azimuth

- _n_s_displacement_ uses an azimuth of 0

- _e_w_displacement_ uses an azimuth of 90

Thank you for the reminder to getting around this.
