### ISSUE TITLE
get_iers fails downloading IERS bulletins

### ISSUE THREAD

**Issue by kohlerjl** [jkennel/earthtide#2]
The URLs 'ftp://ftp.iers.org/...' hard-coded in the get_iers_a function no longer seem to be working. I have been able to retrieve the bulletins from 'https://datacenter.iers.org/products/eop/rapid/...'. Would it be possible to add optional parameters to the get_iers function to allow providing alternate source URLs at runtime? It would also be convenient if these functions could also accept local paths, if the files have already been downloaded. 

I would attempt this myself, but I have little experience with R. I've been using this module from Python, however, using the rpy2 bridge.

**Comment by jkennel** [comment]
Thank you for bringing this to my attention!  Current parameters should be updated on github and I will push a version to CRAN sometime this week. The `get_iers` function is quite brittle and I don't expect it to become stable as file locations seem to change often.  I now allow a  user to override hard-coded file locations though.

**Comment by jkennel** [comment]
The new version has been sent to CRAN.
