### ISSUE TITLE
Confirm/document coordinate reference system

### ISSUE THREAD

**Issue by kohlerjl** [jkennel/earthtide#3]
I'm somewhat new to tidal predictions, so this might be a naive question, but can you confirm the definition for the latitude, longitude, and elevation parameters used, e.g. for calc_earthtide or prepare_station. Reviewing the referenced Hartmann and Wenzel paper, it appears their tidal model uses geocentric latitude and radius. 

Given the optional parameters earth_radius and earth_eccen, is it safe to assume that the input coordinates are interpreted as geodetic latitude, longitude, and height above the ellipsoid and converted to geocentric internally?

**Comment by jkennel** [comment]
Thank you for the question.  The latitude, longitude and elevation (ellipsoidal height in meters) use the WGS84 geodetic reference.  You are correct that they are converted to geocentric values internally. I'll add this to the documentation. Thanks again.

**Comment by kohlerjl** [comment]
Thanks for the clarification
